version: '3.7'
services:
  rabbitmq3:
    # image: rabbitmq:3-management
    build: ./rabbitmq
    # restart: always
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  envoy:
    image: envoyproxy/envoy-dev
    volumes:
      # - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/envoy-jwt.yaml:/etc/envoy/envoy.yaml
    ports:
      - 10000:10000
    depends_on:
      - rabbitmq3

  auth:
    build: ./auth
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./auth:/usr/src/auth/
    ports:
      - 8000:8000
    env_file:
      - ./auth/.env.dev
    depends_on:
      - envoy

  bank_accounts:
    build: ./bankAccounts
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./bankAccounts/:/usr/src/bankAccounts/
    ports:
      - 8001:8001
    env_file:
      - ./bankAccounts/.env.dev
    depends_on:
      - envoy

  logger:
    build: ./logger
    command: python consumer.py
    env_file:
      - ./logger/.env.dev
    depends_on:
      - rabbitmq3

networks:
  mynetwork:
    external:
      name: mynetwork