version: '3.7'
services:
  auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth/:/usr/src/auth/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      mynetwork:
        aliases:
          - auth.mynetwork
networks:
  mynetwork:
    external:
      name: mynetwork


